-- Add project workspaces, contributor branches, and version history to CAD Handoff.
-- Existing package rows are preserved in a generated "Legacy CAD Packages" project.

create table public.cad_projects (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 80),
  description text,
  created_by uuid not null default auth.uid(),
  created_by_name text not null,
  created_at timestamptz not null default now()
);

create table public.cad_branches (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.cad_projects(id) on delete cascade,
  name text not null check (char_length(trim(name)) between 1 and 80),
  owner_id uuid not null default auth.uid(),
  owner_name text not null,
  branched_from_file_name text,
  merged_at timestamptz,
  created_at timestamptz not null default now()
);

alter table public.cad_packages
  add column project_id bigint references public.cad_projects(id) on delete cascade,
  add column branch_id bigint references public.cad_branches(id) on delete cascade,
  add column version_number integer,
  add column promoted_at timestamptz;

do $$
declare
  legacy_project_id bigint;
  legacy_branch_id bigint;
  package_owner record;
begin
  if exists (select 1 from public.cad_packages where project_id is null) then
    insert into public.cad_projects (name, description, created_by, created_by_name)
    values (
      'Legacy CAD Packages',
      'Packages uploaded before project workspaces were introduced.',
      (select id from auth.users order by created_at limit 1),
      'CAD Handoff'
    )
    returning id into legacy_project_id;

    for package_owner in
      select distinct coalesce(nullif(trim(owner_name), ''), 'Unknown contributor') as owner_name
      from public.cad_packages
      where project_id is null
    loop
      insert into public.cad_branches (
        project_id,
        name,
        owner_id,
        owner_name
      )
      values (
        legacy_project_id,
        package_owner.owner_name || '''s branch',
        coalesce(
          (
            select id
            from auth.users
            where raw_user_meta_data ->> 'username' = package_owner.owner_name
            order by created_at
            limit 1
          ),
          (select id from auth.users order by created_at limit 1)
        ),
        package_owner.owner_name
      )
      returning id into legacy_branch_id;

      with ranked_packages as (
        select
          id,
          row_number() over (order by created_at, id)::integer as version_number
        from public.cad_packages
        where project_id is null
          and coalesce(nullif(trim(owner_name), ''), 'Unknown contributor') = package_owner.owner_name
      )
      update public.cad_packages as cad_package
      set
        project_id = legacy_project_id,
        branch_id = legacy_branch_id,
        version_number = ranked_packages.version_number
      from ranked_packages
      where cad_package.id = ranked_packages.id;
    end loop;
  end if;
end;
$$;

-- If legacy data somehow has multiple primary rows, keep only the newest one.
with ranked_primary_packages as (
  select
    id,
    row_number() over (
      partition by project_id
      order by created_at desc, id desc
    ) as primary_rank
  from public.cad_packages
  where is_primary = true
)
update public.cad_packages as cad_package
set is_primary = false
from ranked_primary_packages
where cad_package.id = ranked_primary_packages.id
  and ranked_primary_packages.primary_rank > 1;

update public.cad_packages
set promoted_at = created_at
where is_primary = true;

alter table public.cad_packages
  alter column project_id set not null,
  alter column branch_id set not null,
  alter column version_number set not null,
  alter column version_number set default 1;

create index cad_branches_project_id_idx
  on public.cad_branches(project_id);

create unique index cad_packages_branch_version_idx
  on public.cad_packages(branch_id, version_number);

create unique index cad_packages_one_primary_per_project_idx
  on public.cad_packages(project_id)
  where is_primary = true;

create index cad_packages_project_created_at_idx
  on public.cad_packages(project_id, created_at desc);

grant select, insert on table public.cad_projects to authenticated;
grant select, insert, update on table public.cad_branches to authenticated;
grant usage, select on sequence public.cad_projects_id_seq to authenticated;
grant usage, select on sequence public.cad_branches_id_seq to authenticated;

alter table public.cad_projects enable row level security;
alter table public.cad_branches enable row level security;

create policy "CAD projects are readable by team members"
on public.cad_projects
for select
to authenticated
using (true);

create policy "Team members can create CAD projects"
on public.cad_projects
for insert
to authenticated
with check ((select auth.uid()) = created_by);

create policy "CAD branches are readable by team members"
on public.cad_branches
for select
to authenticated
using (true);

create policy "Team members can create their own CAD branches"
on public.cad_branches
for insert
to authenticated
with check ((select auth.uid()) = owner_id);

create policy "Branch owners can update their CAD branches"
on public.cad_branches
for update
to authenticated
using ((select auth.uid()) = owner_id)
with check ((select auth.uid()) = owner_id);

create or replace function public.merge_cad_branch(p_branch_id bigint)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  branch_project_id bigint;
  latest_package_id public.cad_packages.id%type;
begin
  select project_id
  into branch_project_id
  from public.cad_branches
  where id = p_branch_id
    and owner_id = (select auth.uid())
    and merged_at is null;

  if branch_project_id is null then
    raise exception 'Only the owner can merge an active branch.';
  end if;

  select id
  into latest_package_id
  from public.cad_packages
  where branch_id = p_branch_id
  order by version_number desc, created_at desc
  limit 1;

  if latest_package_id is null then
    raise exception 'Upload a package version before merging this branch.';
  end if;

  update public.cad_packages
  set is_primary = false
  where project_id = branch_project_id
    and is_primary = true;

  update public.cad_packages
  set
    is_primary = true,
    promoted_at = now()
  where id = latest_package_id;

  update public.cad_branches
  set merged_at = now()
  where id = p_branch_id;
end;
$$;

revoke all on function public.merge_cad_branch(bigint) from public, anon;
grant execute on function public.merge_cad_branch(bigint) to authenticated;
